// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK16pm5wzjTboLoxshtZLRvvYzryLuMmU',
    appId: '1:1007760785812:web:03a973cd99411408a4cf81',
    messagingSenderId: '1007760785812',
    projectId: 'beyondpeaceapp',
    authDomain: 'beyondpeaceapp.firebaseapp.com',
    storageBucket: 'beyondpeaceapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM2Ump4yWUaDFT7vBNJNUqY1AXszd10TI',
    appId: '1:1007760785812:android:4b752baf55a3b482a4cf81',
    messagingSenderId: '1007760785812',
    projectId: 'beyondpeaceapp',
    storageBucket: 'beyondpeaceapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeOm62TEzsAN3JZtI1MAxJDyuhOgrVOdo',
    appId: '1:1007760785812:ios:9b94716fca1f6cb0a4cf81',
    messagingSenderId: '1007760785812',
    projectId: 'beyondpeaceapp',
    storageBucket: 'beyondpeaceapp.appspot.com',
    iosBundleId: 'com.example.beyondpeace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeOm62TEzsAN3JZtI1MAxJDyuhOgrVOdo',
    appId: '1:1007760785812:ios:a5a9558d1c905e51a4cf81',
    messagingSenderId: '1007760785812',
    projectId: 'beyondpeaceapp',
    storageBucket: 'beyondpeaceapp.appspot.com',
    iosBundleId: 'com.example.beyondpeace.RunnerTests',
  );
}
