// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import
'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCiaVnI1ChjvuaUYIDbShC6KytpDUORAo',
    appId: '1:197506292945:web:81adf2c94622badeb0f9f0',
    messagingSenderId: '197506292945',
    projectId: 'beyondpeace-db1bf',
    authDomain: 'beyondpeace-db1bf.firebaseapp.com',
    storageBucket: 'beyondpeace-db1bf.appspot.com',
    measurementId: 'G-MN6FXL035J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPL6EwnrVgeqfjGnTUXNHO3ZCqy3T5SQA',
    appId: '1:197506292945:android:9936d0ec3de058c6b0f9f0',
    messagingSenderId: '197506292945',
    projectId: 'beyondpeace-db1bf',
    storageBucket: 'beyondpeace-db1bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_KQQrR8OSCD6ZP29wZNEK3YnF96t3HQo',
    appId: '1:197506292945:ios:7796410ce5daffd1b0f9f0',
    messagingSenderId: '197506292945',
    projectId: 'beyondpeace-db1bf',
    storageBucket: 'beyondpeace-db1bf.appspot.com',
    iosClientId: '197506292945-19sgerh703vgupgn2fjg9qovdufodj1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.beyondpeace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_KQQrR8OSCD6ZP29wZNEK3YnF96t3HQo',
    appId: '1:197506292945:ios:afcf9d885bdc8ba3b0f9f0',
    messagingSenderId: '197506292945',
    projectId: 'beyondpeace-db1bf',
    storageBucket: 'beyondpeace-db1bf.appspot.com',
    iosClientId: '197506292945-n879eulra93c9mrfj63s4vqbfu8pb7ap.apps.googleusercontent.com',
    iosBundleId: 'com.example.beyondpeace.RunnerTests',
  );
}
